baseURL: "https://voges.github.io/"
languageCode: "en-us"
title: "Dr. Jan Voges"
theme: "vanilla"

params:
  footer: "&copy; {Year} Jan Voges | [Legal Notice](/legal-notice/)"

menu:
  main:
    - name: Home
      pageRef: /
      weight: 1
    - name: CV
      pageRef: /cv/
      weight: 2
    - name: Publications
      pageRef: /publications/
      weight: 3
    - name: Live
      pageRef: /live/
      weight: 4
